#include <stdlib.h>
#include <stdio.h>

#include <ctype.h>

#include <dirent.h>
#include <regex.h>

#define IMAGE_ASSET_LOCATION "assets"
#define IMAGE_FORMAT_REGEX ".png"
#define ASSET_HEADER_LOCATION "game/glFunctions/headers/texturesList.h"

regex_t regex;

// Returns the position of the null character in the given string
int stringSize(char *str){
    int i = 0;
    while(str[i]){
        i++;
    }
    return i;
}

// Cut string
void cutString(char* str, int pos){
    str[pos] = 0;
}

// Clones the source string to the destination given the destination is large enough
void cloneString(char* src, char* dest){
    int i = 0;
    while((dest[i] = src[i])){
        i++;
    }
}

// Adds two strings together, puts the second string after the first assuming there is space
void concatString(char* first, char* second){
    char c;
    int i = -1;
    do{
        i++;
        c = first[i];
    }while(c);

    first[i] = '/';
    i++;

    int i2 = 0;
    while(second[i2]){
        first[i] = second[i2];
        i++;
        i2++;
    }
    first[i] = 0;
}

void toUpper(char* str){
    for(; *str; str++){
        if(islower(*str)){
            *str += 'A' - 'a';
        }
    }
}

int filter(const struct dirent* dir){
    if (!dir){
        return 0;
    }
    
    return !regexec(&regex, dir->d_name, 0, NULL, 0) || dir->d_type == DT_DIR;
}

void getAllImageFiles(char* directory, FILE* outFile){
    struct dirent **fileList;

    int numFiles = scandir(directory, &fileList, filter, alphasort);

    for(int i = 0; i < numFiles && i < 2; i++){
        free(fileList[i]);
    }
    for(int i = 2; i < numFiles; i++){
        if(fileList[i]->d_type != DT_REG){
            char directoryPath[PATH_MAX];
            cloneString(directory, directoryPath);

            concatString(directoryPath, fileList[i]->d_name);
            getAllImageFiles(directoryPath, outFile);
        }else{
            // Cutting off the extension of the file and putting it in all caps
            int strSize = stringSize(fileList[i]->d_name);
            cutString(fileList[i]->d_name, strSize - 4);
            toUpper(fileList[i]->d_name);

            fprintf(outFile, "  %s,\n", fileList[i]->d_name);
        }
        free(fileList[i]);
    }

    free(fileList);
}

int main(void){
    // Setting up regex for the filter so I only have to do it once
    if (regcomp(&regex, IMAGE_FORMAT_REGEX, 0)){
        printf("ERROR: Couldn't compile regex for finding image files\n");
        exit(203);
    }

    FILE* out = fopen(ASSET_HEADER_LOCATION, "w");
    fprintf(out, "//This file is generated by findAssets.c. It contains an enum of all of the names of assets.\n");
    fprintf(out, "enum AssetNames{\n");

    getAllImageFiles(IMAGE_ASSET_LOCATION, out);

    fprintf(out, "  NUM_ASSETS\n};");
    fclose(out);
}